/**
 * Lesson Part Repository
 * Handles persistence of lesson part records (plannable lesson structure).
 * ID generation is delegated to AdapterRepository.create() via the pending-context pattern.
 */

import { AdapterRepository } from '@viccoboard/storage';
import { LessonPart } from '@viccoboard/core';
import type { StorageAdapter } from '@viccoboard/storage';

export class LessonPartRepository extends AdapterRepository<LessonPart> {
  /** Set before create(), cleared after – injects lesson_id / order_index into mapToRow */
  private pendingLessonId = '';
  private pendingOrderIndex = -1;

  constructor(adapter: StorageAdapter) {
    super(adapter, 'lesson_parts');
  }

  mapToEntity(row: any): LessonPart {
    return {
      id: row.id,
      description: row.description,
      duration: row.duration ?? undefined,
      type: row.type || undefined
    };
  }

  mapToRow(entity: Partial<LessonPart>): any {
    const row: any = {};
    if (entity.id !== undefined) row.id = entity.id;
    if (entity.description !== undefined) row.description = entity.description;
    if (entity.duration !== undefined) row.duration = entity.duration;
    if (entity.type !== undefined) row.type = entity.type;
    // Injected by createPart() only – not present during plain updates
    if (this.pendingLessonId) row.lesson_id = this.pendingLessonId;
    if (this.pendingOrderIndex >= 0) row.order_index = this.pendingOrderIndex;
    return row;
  }

  /** Find all parts for a lesson, ordered by order_index. */
  async findByLesson(lessonId: string): Promise<LessonPart[]> {
    const rows = (await this.adapter.getAll('lesson_parts', { lesson_id: lessonId })) as Array<{
      id: string; lesson_id: string; description: string;
      duration?: number; type?: string; order_index: number;
    }>;
    rows.sort((a, b) => (a.order_index ?? 0) - (b.order_index ?? 0));
    return rows.map(row => this.mapToEntity(row));
  }

  /**
   * Create a new lesson part associated with a lesson.
   * ID is generated by the parent AdapterRepository.create().
   */
  async createPart(
    lessonId: string,
    input: Omit<LessonPart, 'id'>,
    orderIndex: number
  ): Promise<LessonPart> {
    this.pendingLessonId = lessonId;
    this.pendingOrderIndex = orderIndex;
    try {
      return await this.create(input);
    } finally {
      this.pendingLessonId = '';
      this.pendingOrderIndex = -1;
    }
  }

  /** Delete all parts for a lesson (call before replacing with updated parts). */
  async deleteByLesson(lessonId: string): Promise<void> {
    const parts = await this.findByLesson(lessonId);
    for (const part of parts) {
      await this.adapter.delete('lesson_parts', part.id);
    }
  }
}
