<template>
  <div class="participation-view">
    <header><button @click="$router.back()">← Zurück</button><h2>{{ category?.name || 'Mitarbeitsbeurteilung' }}</h2><p>Raster Mitarbeit Sport Sek I: fünf Kriterien à 0–3 Punkte plus optionaler Zusatzpunkt.</p></header>
    <p v-if="loading">Daten werden geladen …</p><p v-else-if="error" role="alert">{{ error }}</p>
    <template v-else-if="category"><section class="card"><h3>Mitarbeitsraster</h3><p>Selbsteinschätzung unterstützt das Gespräch; ausschließlich die Lehrkraftpunkte bilden die Note.</p><ul><li v-for="criterion in criteria" :key="criterion.id"><strong>{{ criterion.label }}</strong>: {{ criterion.description }}</li></ul><p>Note 1 ab 14,5 · Note 2 ab 12 · Note 3 ab 9 · Note 4 ab 7 · Note 5 ab 2,5 · Note 6 bei Leistungsverweigerung</p></section>
      <button class="save-all" :disabled="saving || unsaved.size === 0" @click="saveAll">{{ saving ? 'Speichern …' : 'Alle speichern' }}</button>
      <section v-for="student in students" :key="student.id" class="card"><h3>{{ student.firstName }} {{ student.lastName }} <span>{{ total(student.id).toFixed(1) }} Punkte · Note {{ grade(student.id) }}</span></h3><div class="grid"><strong>Kriterium</strong><strong>Selbst</strong><strong>Lehrkraft</strong><template v-for="criterion in criteria" :key="criterion.id"><label :for="`${student.id}-${criterion.id}-teacher`"><strong>{{ criterion.label }}</strong><small>{{ criterion.description }}</small></label><select :value="score(student.id, 'selfAssessment', criterion.id)" @change="setScore(student.id, 'selfAssessment', criterion.id, $event)"><option value="">–</option><option v-for="n in 4" :key="n" :value="n - 1">{{ n - 1 }}</option></select><select :id="`${student.id}-${criterion.id}-teacher`" :value="score(student.id, 'teacherAssessment', criterion.id)" @change="setScore(student.id, 'teacherAssessment', criterion.id, $event)"><option value="">–</option><option v-for="n in 4" :key="n" :value="n - 1">{{ n - 1 }}</option></select></template></div><label class="bonus"><input type="checkbox" :checked="assessment(student.id).bonusPoint" @change="setBonus(student.id, $event)"> Zusatzpunkt für besonderes Engagement</label><label>Verbalbeurteilung<textarea :value="notes.get(student.id) ?? ''" rows="3" @input="setNote(student.id, $event)" @blur="save(student.id)" /></label></section>
    </template>
  </div>
</template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import type { Sport } from '@viccoboard/core'
import { useSportBridge } from '../composables/useSportBridge'
import { useStudents } from '../composables/useStudentsBridge'
import { PARTICIPATION_CRITERIA, emptyParticipationAssessment, isParticipationAssessment, participationGrade, participationTotal, type ParticipationAssessment, type ParticipationCriterionId } from '../utils/participation-rubric'
const route = useRoute(); const { SportBridge, gradeCategories, performanceEntries } = useSportBridge(); const { repository } = useStudents(); const categoryId = route.params.id as string
const category = ref<Sport.GradeCategory | null>(null); const students = ref<Array<{id:string;firstName:string;lastName:string}>>([]); const assessments = ref(new Map<string, ParticipationAssessment>()); const notes = ref(new Map<string,string>()); const entryIds = ref(new Map<string,string>()); const unsaved = ref(new Set<string>()); const loading = ref(true); const saving = ref(false); const error = ref<string | null>(null); const criteria = PARTICIPATION_CRITERIA
function assessment(id:string) { return assessments.value.get(id) ?? emptyParticipationAssessment() }; function score(id:string, type:'selfAssessment'|'teacherAssessment', criterion:ParticipationCriterionId) { return assessment(id)[type][criterion] ?? '' }; function total(id:string) { return participationTotal(assessment(id)) }; function grade(id:string) { return participationGrade(total(id)) }
function setScore(id:string,type:'selfAssessment'|'teacherAssessment',criterion:ParticipationCriterionId,event:Event) { const next=assessment(id); const value=(event.target as HTMLSelectElement).value; if(value==='') delete next[type][criterion]; else next[type][criterion]=Number(value); assessments.value.set(id,next); unsaved.value.add(id) }
function setBonus(id:string,event:Event) { const next=assessment(id); next.bonusPoint=(event.target as HTMLInputElement).checked; assessments.value.set(id,next); unsaved.value.add(id) }; function setNote(id:string,event:Event) { notes.value.set(id,(event.target as HTMLTextAreaElement).value); unsaved.value.add(id) }
async function load() { loading.value=true; try { category.value=await gradeCategories.value?.findById(categoryId)??null; if(!category.value) { error.value='Kategorie nicht gefunden'; return }; students.value=await repository.value?.findByClassGroup(category.value.classGroupId)??[]; for(const student of students.value) { const latest=(await performanceEntries.value?.findByStudentAndCategory(student.id,categoryId)??[])[0]; if (latest) entryIds.value.set(student.id, latest.id); const measurement=latest?.measurements as Record<string,unknown>|undefined; if(isParticipationAssessment(measurement?.participation)) assessments.value.set(student.id,measurement.participation); if(typeof measurement?.text==='string') notes.value.set(student.id,measurement.text) } } catch { error.value='Fehler beim Laden der Daten' } finally { loading.value=false } }
async function save(id:string) { if(!unsaved.value.has(id)) return; saving.value=true; try { const value=assessment(id); const update={measurements:{participation:value,text:notes.value.get(id)??''},calculatedGrade:grade(id),metadata:{rubric:value.rubric,totalPoints:total(id),selfAssessment:value.selfAssessment}}; const entryId=entryIds.value.get(id); if (entryId) await SportBridge.value?.performanceEntryRepository.update(entryId, update); else { const entry=await SportBridge.value?.recordGradeUseCase.execute({studentId:id,categoryId,...update}); if(entry) entryIds.value.set(id,entry.id) }; unsaved.value.delete(id) } finally { saving.value=false } }; async function saveAll() { for(const id of [...unsaved.value]) await save(id) }; onMounted(load)
</script>
<style scoped>
.participation-view{max-width:980px;margin:auto;padding:1rem}.participation-view header{margin-bottom:1.25rem}.participation-view button{min-height:40px}.card{background:#fff;border:1px solid #dbe3ed;border-radius:10px;padding:1rem;margin:1rem 0}.card h3{margin-top:0;display:flex;justify-content:space-between;gap:1rem}.card h3 span{color:#075985;font-size:.95rem}.grid{display:grid;grid-template-columns:minmax(190px,1fr) 84px 100px;gap:.5rem;align-items:center}.grid label{display:flex;flex-direction:column}.grid small{color:#64748b}.grid select,textarea{min-height:38px;border:1px solid #cbd5e1;border-radius:6px;padding:.35rem}textarea{width:100%;box-sizing:border-box;display:block;margin-top:.3rem;font:inherit}.bonus{display:block;margin:1rem 0}.save-all{background:#0f766e;color:white;border:0;border-radius:6px;padding:.5rem 1rem}@media(max-width:600px){.grid{grid-template-columns:minmax(120px,1fr) 64px 72px;font-size:.85rem}.card h3{flex-direction:column}}
</style>
